import '../globals.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

export function generateStaticParams() {
  return [{ locale: 'en-US' }, { locale: 'pt-BR' }];
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (
      await import(`../../messages/${locale}.json`)
    ).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className="font-regular xs:px-7 xs:py-4 px-4 py-4 tracking-tight md:px-10 md:py-6">
        <NextIntlClientProvider
          locale={locale}
          messages={messages}
        >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
